apiVersion: v1
kind: ReplicationController
metadata:
  name: worker-rc
spec:
  replicas: 2
  selector:
    name: worker-rc
  template:
    metadata:
      labels:
        name: worker-rc
    spec:
      containers:
        -
          args: 
            - worker.py
          command:
            - python
          env:
            -
              name: AUTHOR
              value: "Sebastian Colomar"
          image: academiaonline/simplilearn-dockercoins:latest-worker
          name: worker-container
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 100m
              memory: 100M
          volumeMounts:
            -
              mountPath: /app/
              name: public
              readOnly: true
          workingDir: /app/
      initContainers:
        -
          args: 
            - https://raw.githubusercontent.com/academiaonline/simplilearn-dockercoins/2021-09/worker/worker.py
          command:
            - wget
          env:
            - 
              name: AUTHOR
              value: "Sebastian Colomar"
          image: library/busybox:1.33.1-uclibc@sha256:febcf61cd6e1ac9628f6ac14fa40836d16f3c6ddef3b303ff0321606e55ddd0b
          name: worker-wget
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 100m
              memory: 100M
          volumeMounts:
            -
              mountPath: /public/
              name: public
              readOnly: false
          workingDir: /public/
      volumes:
        -
          emptyDir:
            medium: Memory
            sizeLimit: 1M
          name: public
